### ISSUE TITLE
Member issue

### ISSUE THREAD

**Issue by leeseongtae** [18-2-SKKU-OSS/2018-2-OSS-E7#3]
The special student, Mr. Jeong Min, went out.
청강생 여정민 학생이 갔습니다.

그에따라 여정민 학생이 맡고 있던 part를 재분배 해야합니다.

**Comment by k12340k** [comment]
새로운 역할 분담에서 여정민학생이 맡았던 부분을 다른 팀원에게 배정했습니다.
