### ISSUE TITLE
발표 준비.

### ISSUE THREAD

**Issue by leeseongtae** [18-2-SKKU-OSS/2018-2-OSS-E7#8]
오늘 발표준비를 시간이 되시는 분들은 수업전에 미리 만나서 준비를 좀 하면 좋겠는데 혹시 다들 시간이 어떠신가요?

**Comment by k12340k** [comment]
오후 3시에 시간되는 팀원끼리 모여서 발표준비를 하겠습니다.

**Comment by leeseongtae** [comment]
3
